export const data = [
    {
        STT: 1,
        Content: "Con cá nào bơi nhanh nhất?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Sinh",
        SubSubject: "Động vật",
        EducationLevel: "Lớp 3",
    },
    {
        STT: 2,
        Content: "Cách xa biển nhất là gì?",
        Type: "Một đáp án",
        Difficult: "Vận dụng cao",
        Subject: "Địa",
        SubSubject: "Thiên nhiên",
        EducationLevel: "Lớp 9",
    },
    {
        STT: 3,
        Content: "Phương trình nhân bảng được tìm ra bởi ai?",
        Type: "Một đáp án",
        Difficult: "Thông hiểu",
        Subject: "Toán",
        SubSubject: "Lịch sử",
        EducationLevel: "Lớp 12",
    },
    {
        STT: 4,
        Content: "Sông lớn nhất thế giới là gì?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Địa",
        SubSubject: "Địa lý",
        EducationLevel: "Lớp 8",
    },
    {
        STT: 5,
        Content: "Viên đá nào được xem là bất tuần?",
        Type: "Một đáp án",
        Difficult: "Vận dụng",
        Subject: "Muôn chiều",
        SubSubject: "Vật lý",
        EducationLevel: "Lớp 11",
    },
    {
        STT: 6,
        Content: "Hoàn vi là gì?",
        Type: "Một đáp án",
        Difficult: "Thông hiểu",
        Subject: "Toán",
        SubSubject: "Toán học",
        EducationLevel: "Lớp 10",
    },
    {
        STT: 7,
        Content: "Tầng quang phối chứa phổ vàng phổ nào?",
        Type: "Một đáp án",
        Difficult: "Vận dụng cao",
        Subject: "Hóa",
        SubSubject: "Hoá học",
        EducationLevel: "Lớp 11",
    },
    {
        STT: 8,
        Content: "Loài vật nào sống ở cách xa biển nhất?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Sinh",
        SubSubject: "Động vật",
        EducationLevel: "Lớp 4",
    },
    {
        STT: 9,
        Content: "Bài hát 'Bai Dai Beach' là của ai?",
        Type: "Một đáp án",
        Difficult: "Thông hiểu",
        Subject: "Anh",
        SubSubject: "Văn hoá",
        EducationLevel: "Lớp 10",
    },
    {
        STT: 10,
        Content: "Mô hình là gì?",
        Type: "Một đáp án",
        Difficult: "Vận dụng",
        Subject: "Toán",
        SubSubject: "Toán học",
        EducationLevel: "Lớp 8",
    },
    {
        STT: 11,
        Content: "Ai là tác giả của tác phẩm 'Chiếc lá cuối cùng'?",
        Type: "Một đáp án",
        Difficult: "Thông hiểu",
        Subject: "Văn",
        SubSubject: "Văn hóa",
        EducationLevel: "Lớp 11",
    },
    {
        STT: 12,
        Content: "Trong thế giới người dân tộc H'Mông, vật gì được xem là linh thiêng?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Lịch sử",
        SubSubject: "Văn hóa",
        EducationLevel: "Lớp 7",
    },
    {
        STT: 13,
        Content: "Nước nào có diện tích lớn nhất thế giới?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Địa",
        SubSubject: "Địa lý",
        EducationLevel: "Lớp 5",
    },
    {
        STT: 14,
        Content: "Khu vực nào được coi là 'điểm nóng' của sự cạnh tranh thương mại và chính trị?",
        Type: "Một đáp án",
        Difficult: "Thông hiểu",
        Subject: "Lịch sử",
        SubSubject: "Địa lí",
        EducationLevel: "Lớp 12",
    },
    {
        STT: 15,
        Content: "Đâu là nơi nổi tiếng với ngành công nghệ thông tin tại Ấn Độ?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Toán",
        SubSubject: "Địa lí",
        EducationLevel: "Lớp 10",
    },
    {
        STT: 16,
        Content: "Thành phố nào được gọi là 'thủ đô văn hóa' của Nhật Bản?",
        Type: "Một đáp án",
        Difficult: "Thông hiểu",
        Subject: "Địa",
        SubSubject: "Văn hóa",
        EducationLevel: "Lớp 9",
    },
    {
        STT: 17,
        Content: "Người Mỹ nổi tiếng với môn thể thao nào?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Thể thao",
        SubSubject: "Văn hóa",
        EducationLevel: "Lớp 6",
    },
    {
        STT: 18,
        Content: "Nước nào được gọi là 'xứ sở của nụ cười'?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Văn",
        SubSubject: "Văn hóa",
        EducationLevel: "Lớp 4",
    },
    {
        STT: 19,
        Content: "Đâu là quốc gia nổi tiếng với thủ đô Bangkok?",
        Type: "Một đáp án",
        Difficult: "Nhận biết",
        Subject: "Địa",
        SubSubject: "Địa lí",
        EducationLevel: "Lớp 6",
    },
    {
        STT: 20,
        Content: "Nền văn minh nào được coi là nền văn minh đầu tiên của nhân loại?",
        Type: "Một đáp án",
        Difficult: "Thông hiểu",
        Subject: "Lịch sử",
        SubSubject: "Văn hóa",
        EducationLevel: "Lớp 8",
    }
];